### ISSUE TITLE
plot.AMMI overwritten by agricolae

### ISSUE THREAD

**Issue by mariachiarapiro** [Biometris/statgenGxE#1]
Dear developers,
I wanted to report an issue I encountered while trying AMMI analysis with your package.
I am working on R version 4.0.4 and among my packages I have agricolae version 1.3-3. When I load statgenGxE I get the following message:

Registered S3 method overwritten by 'agricolae':
  method    from      
  plot.AMMI statgenGxE
  
Indeed, the plot function does not work with the gxeAmmi() output, giving me the following list of error/warnings:
Error in plot.window(...) : need finite 'xlim' values
Inoltre: Warning messages:
1: In min(x, na.rm = na.rm) :
  no non-missing arguments to min; returning Inf
2: In max(x, na.rm = na.rm) :
  no non-missing arguments to max; returning -Inf
3: In min(x, na.rm = na.rm) :
  no non-missing arguments to min; returning Inf
4: In max(x, na.rm = na.rm) :
  no non-missing arguments to max; returning -Inf
5: In plot.window(...) : invalid graphic parameter "plotType"
6: In plot.window(...) : invalid graphic parameter "scale"

Kind regards,
Chiara

**Comment by BartJanvanRossum** [comment]
Dear Chiara,

Indeed the agricolae and statgenGxE both have a function plot.AMMI.
The order in which you load the packages will determine which of the two is actually used when plotting.
If you want to use the plot function from the statgenGxE package load the agricolae package first and then the statgenGxE package:
```r
library(agricolae)
library(statgenGxE)
```
Hope this helps

Regards,
Bart-Jan

**Comment by mariachiarapiro** [comment]
Dear Bart-Jan,
Thank you for the quick reply! This indeed fixed the problem, I did not think of it.

Thanks again, regards
Chiara
